#!/bin/sh
# OpenWrt Version
. /usr/lib/diffserv/functions.sh
. /etc/diffserv.conf

case $1 in 
    up) dscp_start ;
    down) dscp_stop ;;
    restart) dscp_restart ;;
    status) dscp_status ;;
    help) dscp_help;;
esac
