#!/bin/sh
#Debug code in place
. ./codepoints.sh
. ./functions.sh
. ./diffserv.conf

DEBUG_LOG=/tmp/diffserv.$$
ROBUST_STATS=1
dscp_stats=1
ecn_stats=1
icmp6_stats=1

case $1 in 
    up) dscp_start ;;
    down) dscp_stop ;;
    restart) dscp_restart ;;
    status) dscp_status ;;
    help) dscp_help;;
esac
